# config banco de dados
# não vamos utilizar o arquivo padrão de config
spring:
  application:
    name: Gerenciador Hotel
  datasource:
    url: jdbc:h2:mem:gerenciadorhotel
    username: sa
    password: root
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enable: true
      path: /h2-console